name: 01 - Building Blocks

on: push

jobs: 
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello 
              run: echo "Hello, World"
            - name: Failed Step
              run: |
                echo "This step will succeed"
                exit 0
            - name: Say Goodbye
              run: echo "Goodbye, World"