name: 03 - Workflow Runners

on: push

jobs:  
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS 
              run: echo "I'm running on a ${{ runner.os }} runner provided by GitHub Actions."