name: 12 -Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options: [success, failure]
                default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build-step.outputs.status }}    
            output1: ${{ steps.build-step.outputs.output1 }}
            output2: ${{ steps.build-step.outputs.output2 }}
        steps:
            - name: Print GITHUUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT"


            - name: Build
              id: build-step
              #run: echo "status=success" >> $GITHUB_OUTPUT
              run: |
                echo "$GITHUB_OUTPUT"
                echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
                echo "output1=value1" >> $GITHUB_OUTPUT
                echo "output2=value2" >> $GITHUB_OUTPUT
                cat "$GITHUB_OUTPUT"
                echo "mistake=true" > $GITHUB_OUTPUT
                cat "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        if: ${{ needs.build.outputs.build-status == 'success' }}
        needs: build
        steps:
            - name: Deploy
              run: |
                echo "Deploying to production environment..."
            - name: Print Outputs
              run: |               
                echo "Output 1: ${{ needs.build.outputs.output1 }}"
                echo "Output 2: ${{ needs.build.outputs.output2 }}"