name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: 'whether to execute caching step or not'                
                default: true
            node-version:
                description: Node Version
                type: choice
                options: 
                    - 24.15.0
                    - 24.16.0
                default: 24.16.0

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: 13-caching/react-app
    outputs: 
      
      
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    steps:      
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{inputs.node-version}}
      - name: Calculate Cache Key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{hashFiles('13-caching/react-app/package-lock.json')}}" >> "$GITHUB_OUTPUT"
      - name: Download Cached Dependencies
        uses: actions/cache@v5
        if: ${{ inputs.use-cache}}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{steps.cache-key.outputs.CACHE_KEY}}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci # Clean Install:  completely wipe your existing node modules and install dependencies cleanly and exactly.
  lint-test:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
        run:
            working-directory: 13-caching/react-app
    steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - name: Setup Node
          uses: actions/setup-node@v6
          with:
            node-version: ${{inputs.node-version}}        
        - name: Download Cached Dependencies
          uses: actions/cache@v5
          if: ${{ inputs.use-cache}}
          id: cache
          with:
            path: 13-caching/react-app/node_modules
            key:  ${{ needs.install-deps.outputs.deps-cache-key }}
        #3. Unit Testing, Building 
        - name: Testing
          run: npm run test
        - name: Linting
          run: echo "Linting..."
        #4. Deploy to non-prod environment
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
        run:
            working-directory: 13-caching/react-app
    steps:        
        - name: Checkout code
          uses: actions/checkout@v6
        - name: Setup Node
          uses: actions/setup-node@v6
          with:
            node-version: ${{inputs.node-version}}        
        - name: Download Cached Dependencies
          uses: actions/cache@v5
          if: ${{ inputs.use-cache}}
          id: cache
          with:
            path: 13-caching/react-app/node_modules
            key:  ${{ needs.install-deps.outputs.deps-cache-key }}          
        - name: Building
          run: npm run build
        #4. Deploy to non-prod environment
        