name: 15 - Working With Matrices

on:
    workflow_dispatch:

jobs:
    backwards_compatibility:
        name: ${{matrix.os}}-${{matrix.node-version}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false # Default=true, if one job fails in the matrix, all other jobs are skipped.
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os: [ubuntu-latest, windows-latest]
                include: # Allows us to "manually" add a configuration to the matrix.
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-version}}
            - name: Fail if experimental
              if: ${{matrix.tag == 'experimental'}}
              run: exit 1
            - name: Perform Some Tests
              run: |
                echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
                sleep 10
            - name: Upload Test Results
              run: echo "Uploading test results"
    include-example:
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
        runs-on: ubuntu-latest
        strategy:
          matrix:
            color: [red,green]
            shape: [circle,square]            
            size: [small,large]
            include:
              - color: red
                shape: triangle

